# bash main_exp_B.sh
 
# python main_exp.py --n 1 --out_file "results_main/baseline_push_bar.json" --out_dir "results_main/baseline_push_bar" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "push_bar"
# python main_exp.py --n 1 --out_file "results_main/baseline_pick_bar.json" --out_dir "results_main/baseline_pick_bar" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "pick_bar"
# python main_exp.py --n 1 --out_file "results_main/baseline_open_box.json" --out_dir "results_main/baseline_open_box" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "open_box"
# python main_exp.py --n 1 --out_file "results_main/baseline_turn_faucet.json" --out_dir "results_main/baseline_turn_faucet" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "turn_faucet"

# python main_exp.py --n 4 --out_file "results_main/baseline_dino_push_bar_4.json" --out_dir "results_main/baseline_dino_push_bar_4" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_bar"
# python main_exp.py --n 4 --out_file "results_main/baseline_dino_pick_bar_4.json" --out_dir "results_main/baseline_dino_pick_bar_4" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "pick_bar"
# python main_exp.py --n 4 --out_file "results_main/baseline_dino_open_box_4.json" --out_dir "results_main/baseline_dino_open_box_4" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "open_box"
# python main_exp.py --n 4 --out_file "results_main/baseline_dino_turn_faucet_4.json" --out_dir "results_main/baseline_dino_turn_faucet_4" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet"

python main_exp.py --n 1 --out_file "results_main/baseline_dino_push_bar.json" --out_dir "results_main/baseline_dino_push_bar" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_bar"
python main_exp.py --n 1 --out_file "results_main/baseline_dino_pick_bar.json" --out_dir "results_main/baseline_dino_pick_bar" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "pick_bar"
python main_exp.py --n 1 --out_file "results_main/baseline_dino_open_box.json" --out_dir "results_main/baseline_dino_open_box" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "open_box"
python main_exp.py --n 1 --out_file "results_main/baseline_dino_turn_faucet.json" --out_dir "results_main/baseline_dino_turn_faucet" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet"

# clip
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_push_bar_clip_min_4.json" --out_dir "results_main/new_push_bar_clip_min_4" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "push_bar"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_pick_bar_clip_min_4.json" --out_dir "results_main/new_pick_bar_clip_min_4" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "pick_bar"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_open_box_clip_min_4.json" --out_dir "results_main/new_open_box_clip_min_4" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "open_box"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_clip_min_4.json" --out_dir "results_main/new_turn_faucet_clip_min_4" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "turn_faucet"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_clip_min_4.json" --out_dir "results_main/new_turn_faucet_clip_min_4" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "turn_faucet"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_clip_min_4.json" --out_dir "results_main/new_turn_faucet_clip_min_4" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "turn_faucet"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_clip_min_4.json" --out_dir "results_main/new_turn_faucet_clip_min_4" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "turn_faucet"

# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_push_bar_clip_min_4_refine40.json" --out_dir "results_main/new_push_bar_clip_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "push_bar" --refine_step 40
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_pick_bar_clip_min_4_refine40.json" --out_dir "results_main/new_pick_bar_clip_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "pick_bar" --refine_step 40
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_open_box_clip_min_4_refine40.json" --out_dir "results_main/new_open_box_clip_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "open_box" --refine_step 40
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_clip_min_4_refine40.json" --out_dir "results_main/new_turn_faucet_clip_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "turn_faucet" --refine_step 40
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_clip_min_4_refine40.json" --out_dir "results_main/new_turn_faucet_clip_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "turn_faucet" --refine_step 40
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_clip_min_4_refine40.json" --out_dir "results_main/new_turn_faucet_clip_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "turn_faucet" --refine_step 40
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_clip_min_4_refine40.json" --out_dir "results_main/new_turn_faucet_clip_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "turn_faucet" --refine_step 40

# dinov2
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_push_bar_dinov2_min_4.json" --out_dir "results_main/new_push_bar_dinov2_min_4" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_bar"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_pick_bar_dinov2_min_4.json" --out_dir "results_main/new_pick_bar_dinov2_min_4" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "pick_bar"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_open_box_dinov2_min_4.json" --out_dir "results_main/new_open_box_dinov2_min_4" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "open_box"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_dinov2_min_4.json" --out_dir "results_main/new_turn_faucet_dinov2_min_4" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_dinov2_min_4.json" --out_dir "results_main/new_turn_faucet_dinov2_min_4" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_dinov2_min_4.json" --out_dir "results_main/new_turn_faucet_dinov2_min_4" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_dinov2_min_4.json" --out_dir "results_main/new_turn_faucet_dinov2_min_4" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_push_alphabet_dinov2_min_4.json" --out_dir "results_main/new_push_alphabet_dinov2_min_4" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_alphabet"

# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_push_bar_dinov2_min_4_refine40.json" --out_dir "results_main/new_push_bar_dinov2_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_bar" --refine_step 40
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_pick_bar_dinov2_min_4_refine40.json" --out_dir "results_main/new_pick_bar_dinov2_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "pick_bar" --refine_step 40
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_open_box_dinov2_min_4_refine40.json" --out_dir "results_main/new_open_box_dinov2_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "open_box" --refine_step 40
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_dinov2_min_4_refine40.json" --out_dir "results_main/new_turn_faucet_dinov2_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 40
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_dinov2_min_4_refine40.json" --out_dir "results_main/new_turn_faucet_dinov2_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 40
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_dinov2_min_4_refine40.json" --out_dir "results_main/new_turn_faucet_dinov2_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 40
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_dinov2_min_4_refine40.json" --out_dir "results_main/new_turn_faucet_dinov2_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 40



python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_push_bar_dinov2_min.json" --out_dir "results_main/new_push_bar_dinov2_min_1" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_bar" --refine_step 0
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_pick_bar_dinov2_min.json" --out_dir "results_main/new_pick_bar_dinov2_min_1" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "pick_bar" --refine_step 0
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_open_box_dinov2_min.json" --out_dir "results_main/new_open_box_dinov2_min_1" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "open_box" --refine_step 0
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 0
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 0
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 0
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 0

python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_push_bar_dinov2_min_1_refine40.json" --out_dir "results_main/new_push_bar_dinov2_min_1_refine40" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_bar" --refine_step 40
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_pick_bar_dinov2_min_1_refine40.json" --out_dir "results_main/new_pick_bar_dinov2_min_1_refine40" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "pick_bar" --refine_step 40
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_open_box_dinov2_min_1_refine40.json" --out_dir "results_main/new_open_box_dinov2_min_1_refine40" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "open_box" --refine_step 40
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine40.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine40" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 40
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine40.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine40" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 40
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine40.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine40" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 40
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine40.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine40" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 40

python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_push_bar_dinov2_min_1_refine40_scratch.json" --out_dir "results_main/new_push_bar_dinov2_min_1_refine40_scratch" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_bar" --refine_step 40 --refine_from_scratch
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_pick_bar_dinov2_min_1_refine40_scratch.json" --out_dir "results_main/new_pick_bar_dinov2_min_1_refine40_scratch" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "pick_bar" --refine_step 40 --refine_from_scratch
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_open_box_dinov2_min_1_refine40_scratch.json" --out_dir "results_main/new_open_box_dinov2_min_1_refine40_scratch" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "open_box" --refine_step 40 --refine_from_scratch
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine40_scratch.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine40_scratch" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 40 --refine_from_scratch
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine40_scratch.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine40_scratch" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 40 --refine_from_scratch 
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine40_scratch.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine40_scratch" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 40 --refine_from_scratch 
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine40_scratch.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine40_scratch" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 40 --refine_from_scratch 

python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_push_bar_dinov2_min_1_refine100.json" --out_dir "results_main/new_push_bar_dinov2_min_1_refine100" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_bar" --refine_step 100
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_pick_bar_dinov2_min_1_refine100.json" --out_dir "results_main/new_pick_bar_dinov2_min_1_refine100" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "pick_bar" --refine_step 100
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_open_box_dinov2_min_1_refine100.json" --out_dir "results_main/new_open_box_dinov2_min_1_refine100" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "open_box" --refine_step 100
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine100.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine100" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 100
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine100.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine100" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 100
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine100.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine100" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 100
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine100.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine100" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 100

python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_push_bar_dinov2_min_1_refine100_scratch.json" --out_dir "results_main/new_push_bar_dinov2_min_1_refine100_scratch" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_bar" --refine_step 100 --refine_from_scratch
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_pick_bar_dinov2_min_1_refine100_scratch.json" --out_dir "results_main/new_pick_bar_dinov2_min_1_refine100_scratch" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "pick_bar" --refine_step 100 --refine_from_scratch
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_open_box_dinov2_min_1_refine100_scratch.json" --out_dir "results_main/new_open_box_dinov2_min_1_refine100_scratch" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "open_box" --refine_step 100 --refine_from_scratch
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine100_scratch.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine100_scratch" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 100 --refine_from_scratch
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine100_scratch.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine100_scratch" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 100 --refine_from_scratch
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine100_scratch.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine100_scratch" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 100 --refine_from_scratch
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine100_scratch.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine100_scratch" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 100 --refine_from_scratch

python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_push_bar_dinov2_min_1_refine200.json" --out_dir "results_main/new_push_bar_dinov2_min_1_refine200" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_bar" --refine_step 200
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_pick_bar_dinov2_min_1_refine200.json" --out_dir "results_main/new_pick_bar_dinov2_min_1_refine200" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "pick_bar" --refine_step 200
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_open_box_dinov2_min_1_refine200.json" --out_dir "results_main/new_open_box_dinov2_min_1_refine200" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "open_box" --refine_step 200
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine200.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine200" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 200
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine200.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine200" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 200
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine200.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine200" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 200
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine200.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine200" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 200

python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_push_bar_dinov2_min_1_refine200_scratch.json" --out_dir "results_main/new_push_bar_dinov2_min_1_refine200_scratch" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_bar" --refine_step 200 --refine_from_scratch
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_pick_bar_dinov2_min_1_refine200_scratch.json" --out_dir "results_main/new_pick_bar_dinov2_min_1_refine200_scratch" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "pick_bar" --refine_step 200 --refine_from_scratch
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_open_box_dinov2_min_1_refine200_scratch.json" --out_dir "results_main/new_open_box_dinov2_min_1_refine200_scratch" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "open_box" --refine_step 200 --refine_from_scratch
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine200_scratch.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine200_scratch" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 200 --refine_from_scratch
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine200_scratch.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine200_scratch" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 200 --refine_from_scratch
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine200_scratch.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine200_scratch" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 200 --refine_from_scratch
python main_exp.py --retrieve_on --n 1 --out_file "results_main/new_turn_faucet_dinov2_min_1_refine200_scratch.json" --out_dir "results_main/new_turn_faucet_dinov2_min_1_refine200_scratch" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 200 --refine_from_scratch


# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_push_bar_clip_min_4_refine100.json" --out_dir "results_main/new_push_bar_clip_min_4_refine100" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "push_bar" --refine_step 100
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_pick_bar_clip_min_4_refine100.json" --out_dir "results_main/new_pick_bar_clip_min_4_refine100" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "pick_bar" --refine_step 100
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_open_box_clip_min_4_refine100.json" --out_dir "results_main/new_open_box_clip_min_4_refine100" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "open_box" --refine_step 100
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_clip_min_4_refine100.json" --out_dir "results_main/new_turn_faucet_clip_min_4_refine100" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "turn_faucet" --refine_step 100
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_clip_min_4_refine100.json" --out_dir "results_main/new_turn_faucet_clip_min_4_refine100" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "turn_faucet" --refine_step 100
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_clip_min_4_refine100.json" --out_dir "results_main/new_turn_faucet_clip_min_4_refine100" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "turn_faucet" --refine_step 100
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_clip_min_4_refine100.json" --out_dir "results_main/new_turn_faucet_clip_min_4_refine100" --temperature 0.3 --agg_metric "min" --enc_method "clip" --task_name "turn_faucet" --refine_step 100

# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_push_bar_dinov2_min_4_refine100.json" --out_dir "results_main/new_push_bar_dinov2_min_4_refine100" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_bar" --refine_step 100
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_pick_bar_dinov2_min_4_refine100.json" --out_dir "results_main/new_pick_bar_dinov2_min_4_refine100" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "pick_bar" --refine_step 100
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_open_box_dinov2_min_4_refine100.json" --out_dir "results_main/new_open_box_dinov2_min_4_refine100" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "open_box" --refine_step 100
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_dinov2_min_4_refine100.json" --out_dir "results_main/new_turn_faucet_dinov2_min_4_refine100" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 100
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_dinov2_min_4_refine100.json" --out_dir "results_main/new_turn_faucet_dinov2_min_4_refine100" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 100
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_dinov2_min_4_refine100.json" --out_dir "results_main/new_turn_faucet_dinov2_min_4_refine100" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 100
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_dinov2_min_4_refine100.json" --out_dir "results_main/new_turn_faucet_dinov2_min_4_refine100" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --refine_step 100




# dinov2
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_new_turn_faucet_dinov2_min_4.json" --out_dir "results_main/new_new_turn_faucet_dinov2_min_4" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_new_turn_faucet_dinov2_min_4.json" --out_dir "results_main/new_new_turn_faucet_dinov2_min_4" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_new_turn_faucet_dinov2_min_4.json" --out_dir "results_main/new_new_turn_faucet_dinov2_min_4" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_new_turn_faucet_dinov2_min_4.json" --out_dir "results_main/new_new_turn_faucet_dinov2_min_4" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_new_pick_bar_dinov2_min_4.json" --out_dir "results_main/new_new_pick_bar_dinov2_min_4" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "pick_bar"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_new_open_box_dinov2_min_4.json" --out_dir "results_main/new_new_open_box_dinov2_min_4" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "open_box"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_new_push_bar_dinov2_min_4.json" --out_dir "results_main/new_new_push_bar_dinov2_min_4" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_bar"

# # r3m
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_push_bar_r3m_min_4.json" --out_dir "results_main/new_push_bar_r3m_min_4" --temperature 0.3 --agg_metric "min" --enc_method "r3m" --task_name "push_bar"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_pick_bar_r3m_min_4.json" --out_dir "results_main/new_pick_bar_r3m_min_4" --temperature 0.3 --agg_metric "min" --enc_method "r3m" --task_name "pick_bar"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_open_box_r3m_min_4.json" --out_dir "results_main/new_open_box_r3m_min_4" --temperature 0.3 --agg_metric "min" --enc_method "r3m" --task_name "open_box"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_r3m_min_4.json" --out_dir "results_main/new_turn_faucet_r3m_min_4" --temperature 0.3 --agg_metric "min" --enc_method "r3m" --task_name "turn_faucet"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_r3m_min_4.json" --out_dir "results_main/new_turn_faucet_r3m_min_4" --temperature 0.3 --agg_metric "min" --enc_method "r3m" --task_name "turn_faucet"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_r3m_min_4.json" --out_dir "results_main/new_turn_faucet_r3m_min_4" --temperature 0.3 --agg_metric "min" --enc_method "r3m" --task_name "turn_faucet"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_r3m_min_4.json" --out_dir "results_main/new_turn_faucet_r3m_min_4" --temperature 0.3 --agg_metric "min" --enc_method "r3m" --task_name "turn_faucet"

# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_push_bar_r3m_min_4_refine40.json" --out_dir "results_main/new_push_bar_r3m_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "r3m" --task_name "push_bar" --refine_step 40
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_pick_bar_r3m_min_4_refine40.json" --out_dir "results_main/new_pick_bar_r3m_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "r3m" --task_name "pick_bar" --refine_step 40
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_open_box_r3m_min_4_refine40.json" --out_dir "results_main/new_open_box_r3m_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "r3m" --task_name "open_box" --refine_step 40
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_r3m_min_4_refine40.json" --out_dir "results_main/new_turn_faucet_r3m_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "r3m" --task_name "turn_faucet" --refine_step 40
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_r3m_min_4_refine40.json" --out_dir "results_main/new_turn_faucet_r3m_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "r3m" --task_name "turn_faucet" --refine_step 40
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_r3m_min_4_refine40.json" --out_dir "results_main/new_turn_faucet_r3m_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "r3m" --task_name "turn_faucet" --refine_step 40
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/new_turn_faucet_r3m_min_4_refine40.json" --out_dir "results_main/new_turn_faucet_r3m_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "r3m" --task_name "turn_faucet" --refine_step 40


# # custom
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/push_bar_custom_min_4.json" --out_dir "results_main/push_bar_custom_min_4" --temperature 0.3 --agg_metric "min" --enc_method "custom" --task_name "push_bar"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/pick_bar_custom_min_4.json" --out_dir "results_main/pick_bar_custom_min_4" --temperature 0.3 --agg_metric "min" --enc_method "custom" --task_name "pick_bar"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/open_box_custom_min_4.json" --out_dir "results_main/open_box_custom_min_4" --temperature 0.3 --agg_metric "min" --enc_method "custom" --task_name "open_box"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/turn_faucet_custom_min_4.json" --out_dir "results_main/turn_faucet_custom_min_4" --temperature 0.3 --agg_metric "min" --enc_method "custom" --task_name "turn_faucet"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/turn_faucet_custom_min_4.json" --out_dir "results_main/turn_faucet_custom_min_4" --temperature 0.3 --agg_metric "min" --enc_method "custom" --task_name "turn_faucet"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/turn_faucet_custom_min_4.json" --out_dir "results_main/turn_faucet_custom_min_4" --temperature 0.3 --agg_metric "min" --enc_method "custom" --task_name "turn_faucet"
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/turn_faucet_custom_min_4.json" --out_dir "results_main/turn_faucet_custom_min_4" --temperature 0.3 --agg_metric "min" --enc_method "custom" --task_name "turn_faucet"

# python main_exp.py --retrieve_on --n 4 --out_file "results_main/push_bar_custom_min_4_refine40.json" --out_dir "results_main/push_bar_custom_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "custom" --task_name "push_bar" --refine_step 40
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/pick_bar_custom_min_4_refine40.json" --out_dir "results_main/pick_bar_custom_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "custom" --task_name "pick_bar" --refine_step 40
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/open_box_custom_min_4_refine40.json" --out_dir "results_main/open_box_custom_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "custom" --task_name "open_box" --refine_step 40
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/turn_faucet_custom_min_4_refine40.json" --out_dir "results_main/turn_faucet_custom_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "custom" --task_name "turn_faucet" --refine_step 40
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/turn_faucet_custom_min_4_refine40.json" --out_dir "results_main/turn_faucet_custom_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "custom" --task_name "turn_faucet" --refine_step 40
# python main_exp.py --retrieve_on --n 4 --out_file "results_main/turn_faucet_custom_min_4_refine40.json" --out_dir "results_main/turn_faucet_custom_min_4_refine40" --temperature 0.3 --agg_metric "min" --enc_method "custom" --task_name "turn_faucet" --refine_step 40