python main_exp.py -s 400 --n 2 --out_file "final_exp/rej_dino_push.json" --out_dir "final_exp/rej_dino_push" --temperature 0.3 --agg_metric "min" --dist_metric "dinov2" --enc_method "dinov2" --task_name "push_bar" --retrieve_on --refine_step 0
python main_exp.py -s 400 --n 2 --out_file "final_exp/rej_dino_push.json" --out_dir "final_exp/rej_dino_push" --temperature 0.3 --agg_metric "min" --dist_metric "dinov2" --enc_method "dinov2" --task_name "push_bar" --retrieve_on --refine_step 0
python main_exp.py -s 400 --n 2 --out_file "final_exp/rej_dino_push.json" --out_dir "final_exp/rej_dino_push" --temperature 0.3 --agg_metric "min" --dist_metric "dinov2" --enc_method "dinov2" --task_name "push_bar" --retrieve_on --refine_step 0
python main_exp.py -s 400 --n 2 --out_file "final_exp/rej_dino_push.json" --out_dir "final_exp/rej_dino_push" --temperature 0.3 --agg_metric "min" --dist_metric "dinov2" --enc_method "dinov2" --task_name "push_bar" --retrieve_on --refine_step 0

python main_exp.py -s 400 --n 2 --out_file "final_exp/rej_dino_pick.json" --out_dir "final_exp/rej_dino_pick" --temperature 0.3 --agg_metric "min" --dist_metric "dinov2" --enc_method "dinov2" --task_name "pick_bar" --retrieve_on --refine_step 0
python main_exp.py -s 400 --n 2 --out_file "final_exp/rej_dino_pick.json" --out_dir "final_exp/rej_dino_pick" --temperature 0.3 --agg_metric "min" --dist_metric "dinov2" --enc_method "dinov2" --task_name "pick_bar" --retrieve_on --refine_step 0
python main_exp.py -s 400 --n 2 --out_file "final_exp/rej_dino_pick.json" --out_dir "final_exp/rej_dino_pick" --temperature 0.3 --agg_metric "min" --dist_metric "dinov2" --enc_method "dinov2" --task_name "pick_bar" --retrieve_on --refine_step 0
python main_exp.py -s 400 --n 2 --out_file "final_exp/rej_dino_pick.json" --out_dir "final_exp/rej_dino_pick" --temperature 0.3 --agg_metric "min" --dist_metric "dinov2" --enc_method "dinov2" --task_name "pick_bar" --retrieve_on --refine_step 0

python main_exp.py -s 400 --n 2 --out_file "final_exp/rej_dino_open.json" --out_dir "final_exp/rej_dino_open" --temperature 0.3 --agg_metric "min" --dist_metric "dinov2" --enc_method "dinov2" --task_name "open_box" --retrieve_on --refine_step 0
python main_exp.py -s 400 --n 2 --out_file "final_exp/rej_dino_open.json" --out_dir "final_exp/rej_dino_open" --temperature 0.3 --agg_metric "min" --dist_metric "dinov2" --enc_method "dinov2" --task_name "open_box" --retrieve_on --refine_step 0
python main_exp.py -s 400 --n 2 --out_file "final_exp/rej_dino_open.json" --out_dir "final_exp/rej_dino_open" --temperature 0.3 --agg_metric "min" --dist_metric "dinov2" --enc_method "dinov2" --task_name "open_box" --retrieve_on --refine_step 0
python main_exp.py -s 400 --n 2 --out_file "final_exp/rej_dino_open.json" --out_dir "final_exp/rej_dino_open" --temperature 0.3 --agg_metric "min" --dist_metric "dinov2" --enc_method "dinov2" --task_name "open_box" --retrieve_on --refine_step 0

python main_exp.py -s 400 --n 2 --out_file "final_exp/rej_dino_turn.json" --out_dir "final_exp/rej_dino_turn" --temperature 0.3 --agg_metric "min" --dist_metric "dinov2" --enc_method "dinov2" --task_name "turn_faucet" --retrieve_on --refine_step 0
python main_exp.py -s 400 --n 2 --out_file "final_exp/rej_dino_turn.json" --out_dir "final_exp/rej_dino_turn" --temperature 0.3 --agg_metric "min" --dist_metric "dinov2" --enc_method "dinov2" --task_name "turn_faucet" --retrieve_on --refine_step 0
python main_exp.py -s 400 --n 2 --out_file "final_exp/rej_dino_turn.json" --out_dir "final_exp/rej_dino_turn" --temperature 0.3 --agg_metric "min" --dist_metric "dinov2" --enc_method "dinov2" --task_name "turn_faucet" --retrieve_on --refine_step 0
python main_exp.py -s 400 --n 2 --out_file "final_exp/rej_dino_turn.json" --out_dir "final_exp/rej_dino_turn" --temperature 0.3 --agg_metric "min" --dist_metric "dinov2" --enc_method "dinov2" --task_name "turn_faucet" --retrieve_on --refine_step 0