python main_exp.py -s 400 --n 2 --out_file "final_exp/ret_scr_push.json" --out_dir "final_exp/ret_scr_push" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_bar" --retrieve_on --refine_from_scratch --refine_step 100
python main_exp.py -s 400 --n 2 --out_file "final_exp/ret_scr_push.json" --out_dir "final_exp/ret_scr_push" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_bar" --retrieve_on --refine_from_scratch --refine_step 100
python main_exp.py -s 400 --n 2 --out_file "final_exp/ret_scr_push.json" --out_dir "final_exp/ret_scr_push" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_bar" --retrieve_on --refine_from_scratch --refine_step 100
python main_exp.py -s 400 --n 2 --out_file "final_exp/ret_scr_push.json" --out_dir "final_exp/ret_scr_push" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_bar" --retrieve_on --refine_from_scratch --refine_step 100

python main_exp.py -s 400 --n 2 --out_file "final_exp/ret_scr_pick.json" --out_dir "final_exp/ret_scr_pick" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "pick_bar" --retrieve_on --refine_from_scratch --refine_step 100
python main_exp.py -s 400 --n 2 --out_file "final_exp/ret_scr_pick.json" --out_dir "final_exp/ret_scr_pick" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "pick_bar" --retrieve_on --refine_from_scratch --refine_step 100
python main_exp.py -s 400 --n 2 --out_file "final_exp/ret_scr_pick.json" --out_dir "final_exp/ret_scr_pick" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "pick_bar" --retrieve_on --refine_from_scratch --refine_step 100
python main_exp.py -s 400 --n 2 --out_file "final_exp/ret_scr_pick.json" --out_dir "final_exp/ret_scr_pick" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "pick_bar" --retrieve_on --refine_from_scratch --refine_step 100

python main_exp.py -s 400 --n 2 --out_file "final_exp/ret_scr_open.json" --out_dir "final_exp/ret_scr_open" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "open_box" --retrieve_on --refine_from_scratch --refine_step 100
python main_exp.py -s 400 --n 2 --out_file "final_exp/ret_scr_open.json" --out_dir "final_exp/ret_scr_open" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "open_box" --retrieve_on --refine_from_scratch --refine_step 100
python main_exp.py -s 400 --n 2 --out_file "final_exp/ret_scr_open.json" --out_dir "final_exp/ret_scr_open" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "open_box" --retrieve_on --refine_from_scratch --refine_step 100
python main_exp.py -s 400 --n 2 --out_file "final_exp/ret_scr_open.json" --out_dir "final_exp/ret_scr_open" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "open_box" --retrieve_on --refine_from_scratch --refine_step 100

python main_exp.py -s 400 --n 2 --out_file "final_exp/ret_scr_turn.json" --out_dir "final_exp/ret_scr_turn" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --retrieve_on --refine_from_scratch --refine_step 100
python main_exp.py -s 400 --n 2 --out_file "final_exp/ret_scr_turn.json" --out_dir "final_exp/ret_scr_turn" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --retrieve_on --refine_from_scratch --refine_step 100
python main_exp.py -s 400 --n 2 --out_file "final_exp/ret_scr_turn.json" --out_dir "final_exp/ret_scr_turn" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --retrieve_on --refine_from_scratch --refine_step 100
python main_exp.py -s 400 --n 2 --out_file "final_exp/ret_scr_turn.json" --out_dir "final_exp/ret_scr_turn" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet" --retrieve_on --refine_from_scratch --refine_step 100