python main_exp.py -g -3.0 -rg 0.0 -s 100 --refine_step 0 --retrieve_on --n 4 --out_file "results_main/all_ng_open_box_random_000.json" --out_dir "results_main/all_ng_open_box_random_000" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "open_box"
# python main_exp.py -g 3 -rg 0.0 -s 100 --refine_step 100 --refine_from_scratch --retrieve_on --n 4 --out_file "results_main/all_g_open_box_random_000.json" --out_dir "results_main/all_g_open_box_random_000" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "open_box"

# python main_exp.py -g 3 -rg 0.0 -s 100 --refine_step 100 --refine_from_scratch --retrieve_on --n 4 --out_file "results_main/all_g_pick_bar_random_000.json" --out_dir "results_main/all_g_pick_bar_random_000" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "pick_bar"
# python main_exp.py -g 3 -rg 0.0 -s 100 --refine_step 100 --refine_from_scratch --retrieve_on --n 4 --out_file "results_main/all_g_pick_bar_random_000.json" --out_dir "results_main/all_g_pick_bar_random_000" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "pick_bar"


# python main_exp.py -g 3 -rg 0.0 -s 100 --refine_step 100 --refine_from_scratch --retrieve_on --n 4 --out_file "results_main/all_g_turn_faucet_random_000.json" --out_dir "results_main/all_g_turn_faucet_random_000" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet"
# python main_exp.py -g 3 -rg 0.0 -s 100 --refine_step 100 --refine_from_scratch --retrieve_on --n 4 --out_file "results_main/all_g_turn_faucet_random_000.json" --out_dir "results_main/all_g_turn_faucet_random_000" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet"
# python main_exp.py -g 3 -rg 0.0 -s 100 --refine_step 100 --refine_from_scratch --retrieve_on --n 4 --out_file "results_main/all_g_turn_faucet_random_000.json" --out_dir "results_main/all_g_turn_faucet_random_000" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet"
# python main_exp.py -g 3 -rg 0.0 -s 100 --refine_step 100 --refine_from_scratch --retrieve_on --n 4 --out_file "results_main/all_g_turn_faucet_random_000.json" --out_dir "results_main/all_g_turn_faucet_random_000" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet"

# python main_exp.py -g 3 -rg 0.0 -s 100 --refine_step 100 --refine_from_scratch --retrieve_on --n 4 --out_file "results_main/all_g_push_bar_random_000.json" --out_dir "results_main/all_g_push_bar_random_000" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_bar"
# python main_exp.py -g 3 -rg 0.0 -s 100 --refine_step 100 --refine_from_scratch --retrieve_on --n 4 --out_file "results_main/all_g_push_bar_random_000.json" --out_dir "results_main/all_g_push_bar_random_000" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_bar"
