python main_exp.py -rg 0.5 -s 100 --refine_step 100 --refine_from_scratch --retrieve_on --n 4 --out_file "results_main/all_open_box_random_050.json" --out_dir "results_main/all_open_box_random_050" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "open_box"
python main_exp.py -rg 0.5 -s 100 --refine_step 100 --refine_from_scratch --retrieve_on --n 4 --out_file "results_main/all_open_box_random_050.json" --out_dir "results_main/all_open_box_random_050" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "open_box"

python main_exp.py -rg 0.5 -s 100 --refine_step 100 --refine_from_scratch --retrieve_on --n 4 --out_file "results_main/all_pick_bar_random_050.json" --out_dir "results_main/all_pick_bar_random_050" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "pick_bar"
python main_exp.py -rg 0.5 -s 100 --refine_step 100 --refine_from_scratch --retrieve_on --n 4 --out_file "results_main/all_pick_bar_random_050.json" --out_dir "results_main/all_pick_bar_random_050" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "pick_bar"


python main_exp.py -rg 0.5 -s 100 --refine_step 100 --refine_from_scratch --retrieve_on --n 4 --out_file "results_main/all_turn_faucet_random_050.json" --out_dir "results_main/all_turn_faucet_random_050" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet"
python main_exp.py -rg 0.5 -s 100 --refine_step 100 --refine_from_scratch --retrieve_on --n 4 --out_file "results_main/all_turn_faucet_random_050.json" --out_dir "results_main/all_turn_faucet_random_050" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet"
python main_exp.py -rg 0.5 -s 100 --refine_step 100 --refine_from_scratch --retrieve_on --n 4 --out_file "results_main/all_turn_faucet_random_050.json" --out_dir "results_main/all_turn_faucet_random_050" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet"
python main_exp.py -rg 0.5 -s 100 --refine_step 100 --refine_from_scratch --retrieve_on --n 4 --out_file "results_main/all_turn_faucet_random_050.json" --out_dir "results_main/all_turn_faucet_random_050" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet"

python main_exp.py -rg 0.5 -s 100 --refine_step 100 --refine_from_scratch --retrieve_on --n 4 --out_file "results_main/all_push_bar_random_050.json" --out_dir "results_main/all_push_bar_random_050" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_bar"
python main_exp.py -rg 0.5 -s 100 --refine_step 100 --refine_from_scratch --retrieve_on --n 4 --out_file "results_main/all_push_bar_random_050.json" --out_dir "results_main/all_push_bar_random_050" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_bar"
