python main_exp.py -rg 0.0 -s 400 --refine_from_scratch --refine_step 100 --retrieve_on --n 4 --out_file "results_main/softmax_all_open_box.json" --out_dir "results_main/softmax_all_open_box" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "open_box"
python main_exp.py -rg 0.0 -s 400 --refine_from_scratch --refine_step 100 --retrieve_on --n 4 --out_file "results_main/softmax_all_open_box.json" --out_dir "results_main/softmax_all_open_box" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "open_box"

python main_exp.py -rg 0.0 -s 400 --refine_from_scratch --refine_step 100 --retrieve_on --n 4 --out_file "results_main/softmax_all_pick_bar.json" --out_dir "results_main/softmax_all_pick_bar" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "pick_bar"
python main_exp.py -rg 0.0 -s 400 --refine_from_scratch --refine_step 100 --retrieve_on --n 4 --out_file "results_main/softmax_all_pick_bar.json" --out_dir "results_main/softmax_all_pick_bar" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "pick_bar"

python main_exp.py -rg 0.0 -s 400 --refine_from_scratch --refine_step 100 --retrieve_on --n 4 --out_file "results_main/softmax_all_turn_faucet.json" --out_dir "results_main/softmax_all_turn_faucet" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet"
python main_exp.py -rg 0.0 -s 400 --refine_from_scratch --refine_step 100 --retrieve_on --n 4 --out_file "results_main/softmax_all_turn_faucet.json" --out_dir "results_main/softmax_all_turn_faucet" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet"
python main_exp.py -rg 0.0 -s 400 --refine_from_scratch --refine_step 100 --retrieve_on --n 4 --out_file "results_main/softmax_all_turn_faucet.json" --out_dir "results_main/softmax_all_turn_faucet" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet"
python main_exp.py -rg 0.0 -s 400 --refine_from_scratch --refine_step 100 --retrieve_on --n 4 --out_file "results_main/softmax_all_turn_faucet.json" --out_dir "results_main/softmax_all_turn_faucet" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "turn_faucet"

python main_exp.py -rg 0.0 -s 400 --refine_from_scratch --refine_step 100 --retrieve_on --n 4 --out_file "results_main/softmax_all_push_bar.json" --out_dir "results_main/softmax_all_push_bar" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_bar"
python main_exp.py -rg 0.0 -s 400 --refine_from_scratch --refine_step 100 --retrieve_on --n 4 --out_file "results_main/softmax_all_push_bar.json" --out_dir "results_main/softmax_all_push_bar" --temperature 0.3 --agg_metric "min" --enc_method "dinov2" --task_name "push_bar"
